environment:
    matrix:
        - nodejs_version: "9"

install:
    - ps: Install-Product node $env:nodejs_version
    - npm Install

test_script:
    - node --version
    - node --version
    - npm test

build: off
